CREATE TABLE ROL (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE,
  descripcion VARCHAR(100)
);
CREATE TABLE CATEGORIA (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  descripcion VARCHAR(100),
  estadoregistro CHAR(1) NOT NULL
);
CREATE TABLE ETIQUETA (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE PROVINCIA (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE
);
CREATE TABLE PASARELAPAGO (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  descripcion VARCHAR(100),
  apikey VARCHAR(100) NOT NULL,
  urlbase VARCHAR(200) NOT NULL,
  logo VARCHAR(200),
  estadoregistro CHAR(1) NOT NULL
);
CREATE TABLE ESTADOGENERAL (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE,
  tipo VARCHAR(30) NOT NULL
);
CREATE TABLE TRANSPORTISTA (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  telefono VARCHAR(20),
  email VARCHAR(60),
  estadoregistro CHAR(1) NOT NULL
);
CREATE TABLE USUARIO (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL,
  email VARCHAR(60) NOT NULL UNIQUE,
  clave VARCHAR(60) NOT NULL,
  telefono VARCHAR(20),
  rol_id BIGINT UNSIGNED NOT NULL,
  estado CHAR(1) NOT NULL,
  FOREIGN KEY (rol_id) REFERENCES ROL(id)
);
CREATE TABLE DISTRITO (
  id BIGINT UNSIGNED PRIMARY KEY,
  provincia_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  FOREIGN KEY (provincia_id) REFERENCES PROVINCIA(id)
);
CREATE TABLE METODOPAGO (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE,
  descripcion VARCHAR(100),
  soportaqr TINYINT(1) NOT NULL,
  pasarelapago_id BIGINT UNSIGNED NOT NULL UNIQUE,
  estadoregistro CHAR(1) NOT NULL,
  FOREIGN KEY (pasarelapago_id) REFERENCES PASARELAPAGO(id)
);
CREATE TABLE CARRITO (
  id BIGINT UNSIGNED PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE,
  fechacreacion DATETIME NOT NULL,
  estadogeneral_id BIGINT UNSIGNED NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
  FOREIGN KEY (estadogeneral_id) REFERENCES ESTADOGENERAL(id)
);
CREATE TABLE VENDEDOR (
  id BIGINT UNSIGNED PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE,
  nombretienda VARCHAR(60) NOT NULL,
  descripcion TEXT,
  logo VARCHAR(200),
  distrito_id BIGINT UNSIGNED NOT NULL,
  estado CHAR(1) NOT NULL,
  FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
  FOREIGN KEY (distrito_id) REFERENCES DISTRITO(id)
);
CREATE TABLE POLITICATIENDA (
  id BIGINT UNSIGNED PRIMARY KEY,
  vendedor_id BIGINT UNSIGNED NOT NULL UNIQUE,
  politicaenvio TEXT,
  politicadevolucion TEXT,
  politicaprivacidad TEXT,
  fechaactualizacion DATETIME NOT NULL,
  estadoregistro CHAR(1) NOT NULL,
  FOREIGN KEY (vendedor_id) REFERENCES VENDEDOR(id)
);
CREATE TABLE PEDIDO (
  id BIGINT UNSIGNED PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  estadogeneral_id BIGINT UNSIGNED NOT NULL,
  fecha DATETIME NOT NULL,
  distrito_id BIGINT UNSIGNED NOT NULL,
  direccionentrega VARCHAR(100) NOT NULL,
  referencia VARCHAR(150),
  metodopago_id BIGINT UNSIGNED NOT NULL,
  vendedor_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
  FOREIGN KEY (estadogeneral_id) REFERENCES ESTADOGENERAL(id),
  FOREIGN KEY (distrito_id) REFERENCES DISTRITO(id),
  FOREIGN KEY (metodopago_id) REFERENCES METODOPAGO(id),
  FOREIGN KEY (vendedor_id) REFERENCES VENDEDOR(id)
);
CREATE TABLE COLECCIONTIENDA (
  id BIGINT UNSIGNED PRIMARY KEY,
  vendedor_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  descripcion VARCHAR(100),
  estadoregistro CHAR(1) NOT NULL,
  FOREIGN KEY (vendedor_id) REFERENCES VENDEDOR(id)
);
CREATE TABLE PAGO (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL UNIQUE,
  metodopago_id BIGINT UNSIGNED NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  fecha DATETIME NOT NULL,
  estadogeneral_id BIGINT UNSIGNED NOT NULL,
  transaccionid VARCHAR(60) UNIQUE,
  urlpasarela VARCHAR(200) NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id),
  FOREIGN KEY (metodopago_id) REFERENCES METODOPAGO(id),
  FOREIGN KEY (estadogeneral_id) REFERENCES ESTADOGENERAL(id)
);
CREATE TABLE ENVIO (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL,
  transportista_id BIGINT UNSIGNED NOT NULL,
  codigoseguimiento VARCHAR(60) UNIQUE,
  estadogeneral_id BIGINT UNSIGNED NOT NULL,
  fechaenvio DATE NOT NULL,
  fechaentrega DATE,
  urlseguimiento VARCHAR(200),
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id),
  FOREIGN KEY (transportista_id) REFERENCES TRANSPORTISTA(id),
  FOREIGN KEY (estadogeneral_id) REFERENCES ESTADOGENERAL(id)
);
CREATE TABLE PRODUCTO (
  id BIGINT UNSIGNED PRIMARY KEY,
  categoria_id BIGINT UNSIGNED NOT NULL,
  vendedor_id BIGINT UNSIGNED NOT NULL,
  colecciontienda_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  descripcion TEXT,
  precio DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  fotoprincipal VARCHAR(200),
  descuento DECIMAL(10,2),
  fechainiciodescuento DATE,
  fechafindescuento DATE,
  activodescuento TINYINT(1) NOT NULL,
  estadoregistro CHAR(1) NOT NULL,
  estado CHAR(1) NOT NULL,
  FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id),
  FOREIGN KEY (vendedor_id) REFERENCES VENDEDOR(id),
  FOREIGN KEY (colecciontienda_id) REFERENCES COLECCIONTIENDA(id)
);
CREATE TABLE PRODUCTOOPCION (
  id BIGINT UNSIGNED PRIMARY KEY,
  producto_id BIGINT UNSIGNED NOT NULL,
  tipo CHAR(1) NOT NULL,
  nombre VARCHAR(60) NOT NULL,
  valor VARCHAR(60) NOT NULL,
  detalle TEXT,
  imagen VARCHAR(200),
  estadoregistro CHAR(1) NOT NULL,
  FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id)
);
CREATE TABLE PEDIDODETALLE (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL,
  producto_id BIGINT UNSIGNED NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  cantidad INT NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id),
  FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id)
);
CREATE TABLE CARRITODETALLE (
  id BIGINT UNSIGNED PRIMARY KEY,
  carrito_id BIGINT UNSIGNED NOT NULL,
  producto_id BIGINT UNSIGNED NOT NULL,
  cantidad INT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (carrito_id) REFERENCES CARRITO(id),
  FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id)
);
CREATE TABLE PRODUCTOETIQUETA (
  id BIGINT UNSIGNED PRIMARY KEY,
  producto_id BIGINT UNSIGNED NOT NULL,
  etiqueta_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id),
  FOREIGN KEY (etiqueta_id) REFERENCES ETIQUETA(id)
);
CREATE TABLE RESENA (
  id BIGINT UNSIGNED PRIMARY KEY,
  producto_id BIGINT UNSIGNED NOT NULL,
  usuario_id BIGINT UNSIGNED NOT NULL,
  puntuacion INT NOT NULL,
  comentario TEXT,
  fecha DATETIME NOT NULL,
  estado CHAR(1) NOT NULL,
  respuestavendedor TEXT,
  FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id),
  FOREIGN KEY (usuario_id) REFERENCES USUARIO(id)
);
CREATE TABLE OPCIONPEDIDO (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedidodetalle_id BIGINT UNSIGNED NOT NULL UNIQUE,
  productoopcion_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (pedidodetalle_id) REFERENCES PEDIDODETALLE(id),
  FOREIGN KEY (productoopcion_id) REFERENCES PRODUCTOOPCION(id)
);
